name: 豆瓣北京租房小组信息爬取

on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 爬虫
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          python main.py

      - name: Commit changes
        run: |
          git config --local user.email "slzhang13@github.com"
          git config --local user.name "slzhang13"
          git pull
          git add .
          git commit -m "爬取后数据更新"
          git push
